# Generated by Django 3.0.1 on 2019-12-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
